version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: sma_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    # Installation des extensions PHP nécessaires
    command: >
      bash -c "
      docker-php-ext-install pdo pdo_mysql mysqli &&
      apache2-foreground
      "
    
  database:
    image: mysql:8.0
    container_name: sma_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sma_database
      MYSQL_USER: sma_user
      MYSQL_PASSWORD: sma_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
